server:
  port: 80

spring:
  datasource:
    #url: jdbc:h2:~/test
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug # SQL ?? ??